### ISSUE TITLE
AttributeError: 'Tilemap' object has no attribute 'manager'

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#74]
# Issue

```
Traceback (most recent call last):
  File "/Users/pdm/Library/Homebrew/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/pdm/Library/Homebrew/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bin/driftwood/__main__.py", line 215, in <module>
  File "bin/driftwood/__main__.py", line 169, in _run
  File "bin/driftwood/inputmanager.py", line 179, in _key_down
  File "bin/driftwood/libs/stdlib/player.py", line 93, in __default_keybind_interact
  File "bin/driftwood/entity.py", line 407, in interact
  File "bin/driftwood/entity.py", line 248, in _tile_at
  File "bin/driftwood/layer.py", line 79, in tile
AttributeError: 'Tilemap' object has no attribute 'manager'
```
# Reproduction

Press spacebar while facing the edge of an area.

**Comment by seisatsu** [comment]
Should be fixed in 26d1cdaf665f0f54332f9e6bdf877d09042cd50f. We check if a tile exists before interacting with it.
